# Generated by Django 4.1 on 2022-10-17 20:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0004_rename_avatar_avatares'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatares',
            new_name='Avatars',
        ),
    ]
