# Generated by Django 4.1 on 2022-10-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_avatars_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirantes',
            name='imgA',
            field=models.ImageField(blank=True, height_field=70, null=True, upload_to='imgA', width_field=70),
        ),
        migrations.AddField(
            model_name='empleados',
            name='imgE',
            field=models.ImageField(blank=True, height_field=70, null=True, upload_to='imgE', width_field=70),
        ),
        migrations.AddField(
            model_name='productos',
            name='imgP',
            field=models.ImageField(blank=True, height_field=70, null=True, upload_to='imgP', width_field=70),
        ),
    ]
