# Generated by Django 4.1 on 2022-10-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_aspirantes_imga_empleados_imge_productos_imgp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirantes',
            name='imgA',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='imgE',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='imgP',
        ),
    ]
