# Generated by Django 4.1 on 2022-10-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_aspirantes_imga_remove_empleados_imge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgP', models.ImageField(blank=True, null=True, upload_to='imgP')),
            ],
        ),
    ]
