# Generated by Django 4.1 on 2022-10-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_imgp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgP',
        ),
    ]
